apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-operator.name" . }}
  labels:
    app: {{ template "couchbase-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.server.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.server.authUsername | b64enc | quote }}
  {{ if .Values.server.authSecret }}
  password:  {{ .Values.server.authSecret | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
