{{ define "config.yaml.tpl" }}
apiVersion: couchbase.database.couchbase.com/v1beta1
kind: CouchbaseCluster
metadata:
  name: {{ .Values.server.name }}
spec:
  baseImage: {{ .Values.server.image.name }}
  version: {{ .Values.server.image.tag }}
  authSecret: {{ .Values.server.authSecret }}
  exposeAdminConsole: {{ .Values.server.exposeAdminConsole }}
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 30
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: {{ .Values.server.replicas }}
      name: all_services
      services:
        - data
        - index
        - query
        - search
      dataPath: /opt/couchbase/var/lib/couchbase/data
      indexPath: /opt/couchbase/var/lib/couchbase/data
{{ end }}
